### ISSUE TITLE
Hello, I found a new problem

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [siosio/kdoc-generator-intellij-plugin#4]
When defining a Kotlin function, if a generic function is used, the generated kdoc will have a generic in addition to the parameters required by the function, but in fact this is unnecessary, it is not a parameter.
![Snipaste_2021-11-04_15-02-59](https://user-images.githubusercontent.com/54784104/140272735-16b65abe-bdbd-480f-ba24-2860904d850e.png)

**Comment by SaltedFish-Extreme** [comment]
Or maybe this annotation is needed?
![image](https://user-images.githubusercontent.com/54784104/140274622-43ece994-3226-49ef-be61-e0c6f1b80d24.png)

**Comment by siosio** [comment]
Generate kdoc based on the document.

* https://kotlinlang.org/docs/kotlin-doc.html#param-name

**Comment by SaltedFish-Extreme** [comment]
> 根据文档生成 kdoc。
> 
> * https://kotlinlang.org/docs/kotlin-doc.html#param-name

Ah, well, since the official regulations are so, there is no way😂
